In [1]:
import numpy as np
from numpy.random import default_rng
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [2]:
rng = np.random.default_rng(12345)

In [3]:
x = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
x[:,2] += 100

In [5]:
x_min = x.min(axis=0)
x_max = x.max(axis=0)

In [6]:
rints = rng.integers(low=x_min, high=x_max, size=(4,3))

In [7]:
rints

array([[  6,   3, 109],
       [  2,   2, 109],
       [  5,   7, 110],
       [  3,   8, 104]])

In [8]:
rfloats = rng.uniform(low=x_min, high=x_max, size=(4,3))

In [9]:
rfloats

array([[  5.38477878,   2.68060767, 108.0548044 ],
       [  8.47622579,   3.23421143, 110.53993037],
       [  6.00513708,   1.86308142, 105.976557  ],
       [  7.97831927,   7.2770815 , 104.93825578]])

In [10]:
rfloats.shape[1]

3

In [11]:
samples = np.array([[0, 0, 2], [1, 0, 0], [0, 0, 1]])
samples

array([[0, 0, 2],
       [1, 0, 0],
       [0, 0, 1]])

In [12]:
neigh = NearestNeighbors(n_neighbors=2)
neigh.fit(samples)

NearestNeighbors(n_neighbors=2)

In [13]:
nni = neigh.kneighbors([[0, 0, 1.3], [0.1, 0, 0], [0.1, 0.1, 1.3]], return_distance=False)
nni

array([[2, 0],
       [1, 2],
       [2, 0]])

In [14]:
nni.shape

(3, 2)

In [15]:
nns = samples[nni]
nns

array([[[0, 0, 1],
        [0, 0, 2]],

       [[1, 0, 0],
        [0, 0, 1]],

       [[0, 0, 1],
        [0, 0, 2]]])

In [16]:
c = np.array([True, False, True], dtype=bool)
c

array([ True, False,  True])

In [17]:
cx = c[nni]
cx

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [20]:
cs = ~cx.all(axis=1)
cs

array([False,  True, False])

In [21]:
nns[cs]

array([[[1, 0, 0],
        [0, 0, 1]]])

In [ ]:
b = np.zeros(10, dtype=bool)
b

In [22]:
nni[cs]

array([[1, 2]])